#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

xrandr --output DP-4 --mode 3840x1600 --rate 144

polybar --reload example &
flameshot &
lxqt-policykit-agent &
xdg-desktop-portal &
xdg-desktop-portal-gtk &

feh --bg-scale ~/Pictures/wet_road.jpg &

